channels:
- conda-forge
dependencies:
- python=3.10.15
- pip<=21.3.1
- pip:
  - mlflow==2.15.1
  - cloudpickle==2.2.1
  - jaraco-collections==5.1.0
  - jaraco-context==5.3.0
  - jaraco-functools==4.0.1
  - jaraco-text==3.12.1
  - more-itertools==10.3.0
  - pandas==1.5.3
  - psutil==5.8.0
  - scikit-learn==1.5.2
name: mlflow-env
