name: GitHub Actions Test
run-name: ${{ github.actor }} workflow test
on: [push]

jobs:
  amlJobSubmission:
    runs-on: ubuntu-latest
    steps:
      # Display event information
      - run: echo "Hi! I'm running because of a ${{ github.event_name }} event."

      # Checkout repository
      - name: Clone repository code
        uses: actions/checkout@v4

      # Azure login
      - name: Log in to Azure
        uses: azure/login@v1.4
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      # Set up Azure ML extension
      - name: Install Azure ML extension
        run: |
          az extension add -n ml -y
          az extension update -n ml

      # Submit the Azure ML job
      - name: Submit Azure ML job
        run: az ml job create --file job.yml --web --resource-group Project-G --workspace-name Project-WS
