name: GitHub Actions Test
run-name: ${{ github.actor }} workflow test
on: [push]

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      # Display event information
      - run: echo "Hi! I'm running because of a ${{ github.event_name }} event."

      # Checkout repository
      - name: Clone repository code
        uses: actions/checkout@v4

      # List files in the repository
      - name: List repository files
        run: ls -l

      # Azure login
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      # Test Azure login
      - name: Verify Azure account details
        run: az account show --query "{Name:name, SubscriptionId:id}" --output table
  AMLJob:
    runs-on: ubuntu-latest
    steps:
      # Azure login
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - run: az extension add --name ml
      - name: Running azure ml job file
        run: az ml job create --file job.yml --web --resource-group Project-G --workspace-name Project-WS